version: "3.7"

services:
  web:
    image: nginx:alpine
    ports:
      - 8081:80
    networks:
      - internal
    volumes:
      - ./webapp:/var/www/webapp
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    image: php:fpm-alpine
    volumes:
      - ./webapp:/var/www/webapp
    networks:
      - internal

networks:
  internal:
    driver: bridge
